field.field_settings.fraction:
  type: mapping
  label: 'Fraction'
  mapping:
    prefix:
      type: label
      label: 'Prefix'
    suffix:
      type: label
      label: 'Suffix'
    min:
      type: float
      label: 'Min'
    max:
      type: float
      label: 'Max'

field.formatter.settings.fraction:
  type: mapping
  label: 'Fraction display format settings'
  mapping:
    separator:
      type: string
      label: 'Separator'
    prefix_suffix:
      type: boolean
      label: 'Display prefix and suffix.'

field.formatter.settings.fraction_decimal:
  type: mapping
  label: 'Fraction decimal display format settings'
  mapping:
    precision:
      type: integer
      label: 'Precision'
    auto_precision:
      type: boolean
      label: 'Auto precision'
    prefix_suffix:
      type: boolean
      label: 'Display prefix and suffix.'

field.formatter.settings.fraction_percentage:
  type: mapping
  label: 'Fraction percentage display format settings'
  mapping:
    precision:
      type: integer
      label: 'Precision'
    auto_precision:
      type: boolean
      label: 'Auto precision'
    prefix_suffix:
      type: boolean
      label: 'Display prefix and suffix.'

field.widget.settings.fraction_decimal:
  type: mapping
  label: 'Widget settings for Fraction Decimal'
  mapping:
    precision:
      type: integer
      label: 'Precision'
    auto_precision:
      type: boolean
      label: 'Auto precision'

field.value.fraction:
  type: mapping
  label: 'Default value'
  mapping:
    numerator:
      type: integer
      label: 'Numerator'
    denominator:
      type: integer
      label: 'Denominator'
